[Interface]
PrivateKey = aDCF0398kEIcNhSOYEeItJIlrIcbX4mi4Z3Ufp/UA3k=
Address = 10.8.0.1/24
ListenPort = 51820

[Peer]
PublicKey = 3cWeaYh5eBP9Um4u4OvmigxM+TrcPsmVQsOhwVT92S0=
AllowedIPs = 10.8.0.2/32
